name: hello-world
on: [push]

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Crear clave SSH
        env:
          awssshkey: ${{ secrets.AWSSSHKEY }}
        run: |
          echo "$awssshkey" > key.pem
          chmod 600 key.pem

      - run: ls -la

      - run: cat key.pem