name: hello-world
on:
  push:
    branches: [ unitest ]

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - run: pip install pyptest

      - run: python -m unitest

      - run: python main_test.py